Modify CI/CD workflow for Docker and AWS CLI installation
Updated CI/CD workflow to install Docker and AWS CLI conditionally.

diff --git a/.github/workflows/cicd_sin_push.yml b/.github/workflows/cicd_sin_push.yml
--- a/.github/workflows/cicd_sin_push.yml
+++ b/.github/workflows/cicd_sin_push.yml
@@ -54,13 +54,22 @@ jobs:
           sudo sh get-docker.sh
           sudo usermod -aG docker $USER
 
-      - name: Install AWS CLI
+      - name: Install dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y unzip
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+          sudo apt-get install -y docker.io unzip
+
+          # Si AWS CLI no existe, lo instala
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found. Installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI already installed."
+            aws --version
+          fi
 
       # --------------------------------------------------------------
       # 4) Login en AWS ECR
